version: '3.8'
services:
  conducteur:
    image: yassinsiouda/conducteur:latest
    build: ./orchestrator
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./id_rsa/conducteur:/root/.ssh/id_rsa
      - ./orchestrator/src/:/app/src/
      - ./data:/app/data
  dashboard:
    profiles:
      - dev
    build: ./dashboard
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./dashboard/src:/app/src