services:
  conducteur:
    image: yassinsiouda/conducteur:webhook
    build: ./orchestrator
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./data/id_rsa/conducteur:/root/.ssh/id_rsa
      - ./orchestrator/src/:/app/src/
      - ./data:/app/data
    # For development purpose to check if thread locks are working 
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
  dashboard:
    profiles:
      - dev
    build: ./dashboard
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./dashboard/src:/app/src