version: '3.8'
services:
  conducteur:
    image: yassinsiouda/conducteur:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./id_rsa/conducteur:/root/.ssh/id_rsa
      - ./data:/app/data